######################################################################
# Automatically generated by qmake (2.01a) ?? 7. ??? 15:11:34 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
RESOURCES = generator.qrc


# Input
HEADERS += mainwindow.h ../engine/generator.h
SOURCES += main.cpp mainwindow.cpp ../engine/generator.cpp
